---
volumes:
  nginxproxymanager-data:
  nginxproxymanager-ssl:
  nginxproxymanager-db:
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:2.10.3
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      - DB_MYSQL_HOST=nginxproxymanager-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=admin
      - DB_MYSQL_PASSWORD=Not4You2C!
      - DB_MYSQL_NAME=npm
    volumes:
      - nginxproxymanager-data:/data
      - nginxproxymanager-ssl:/etc/letsencrypt
    networks:
      - proxy
  nginxproxymanager-db:
    image: jc21/mariadb-aria:10.4.15
    environment:
      - MYSQL_ROOT_PASSWORD=Not4You2C!
      - MYSQL_DATABASE=npm
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Not4You2C!
    volumes:
      - nginxproxymanager-db:/var/lib/mysql
    networks:
      - proxy

networks:
  proxy:
